Story1PPW/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('story1.urls')),
    path('story5/',include('story5.urls')),
    path('story3/', include('story3.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('trialapp/', include('trialapp.urls')),
]

homepage/urls.py
from django.urls import path, include
from . import views

app_name='homepage'

urlpatterns = [
    path('', views.index, name="index"),

]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

story3/urls.py
from django.urls import path

from . import views

app_name = 'story3'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
]

story5/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='story5'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('matkul/<int:pk>/', views.detail, name="detail"),
    path('matkul/<int:pk>/delete', views.delete_matkul, name='delete'),
    path('matkul/', views.matkul_list, name="matkul_list"),
    path('matkul/addmatkul/', views.matkul_add, name="matkul_add"),

]

story6/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='story6'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('tambah/', views.tambah_event, name="tambah_event"),
    path('daftar/<int:id>', views.tambah_attendance, name="tambah_attendance"),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='story7'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
]

story8/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='story8'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('data/', views.fungsi_data, name="data"),
]

trialapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='trialapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('accounts/login/', views.loginPage, name="loginPage"),
    path('accounts/', include('django.contrib.auth.urls')),
    path("target='_blank'", views.blank, name="blank"),
    path('data/', views.fungsi_data, name="data"),
]

story1/models.py
from django.db import models

# Create your models here.

story3/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.
class Matkul(models.Model):
    name = models.CharField(max_length =30)
    dosen = models.CharField(max_length =30)
    total_credit = models.CharField(max_length =30)
    classroom = models.CharField(max_length =30)
    description= models.TextField(max_length =300)

    def __str__(self):
        return self.name

story6/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    event_name = models.CharField(max_length = 50)
    description = models.TextField(max_length = 300)

    def __str__(self):
        return self.event_name

class Attendance(models.Model):
    name = models.CharField(max_length=30)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name ='attendances')

    def __str__(self):
        return self.name 

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story5/forms.py
from django import forms
from .models import Matkul

class MatkulForm(forms.ModelForm):
    class Meta:
        model = Matkul
        fields =('name','dosen','total_credit','classroom','description')

story6/forms.py
from django import forms
from .models import Event,Attendance

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields =('event_name','description')

class AttendanceForm(forms.ModelForm):
    class Meta:
        model = Attendance
        fields =('name',)

trialapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    username = forms.CharField(label="")
    email = forms.CharField(label="")
    password1 = forms.CharField(widget=forms.PasswordInput(),label="")
    password2 = forms.CharField(widget=forms.PasswordInput(),label="")
    username.widget.attrs.update({'placeholder':'username', 'class':'input-box'})
    email.widget.attrs.update({'placeholder':'email', 'class':'input-box'})
    password1.widget.attrs.update({'placeholder':'enter password', 'class':'input-box'})
    password2.widget.attrs.update({'placeholder':'re-enter password', 'class':'input-box'})
    class Meta:
        model = User
        fields = ['username' , 'email', 'password1', 'password2']

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "homepage/index.html")

story1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story1/index.html')

story3/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story3/index.html')

def profile(request):
    return render(request, 'story3/profile.html')

story5/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.core.files.storage import FileSystemStorage
from .forms import MatkulForm
from .models import Matkul

# Create your views here.
def index(request):
    return render(request, "story5/index.html")

def detail(request,pk):
    matkul = Matkul.objects.get(pk=pk)
    return render(request, "story5/detail.html",{
        'matkul': matkul
    })

def matkul_list(request):
    matkul=Matkul.objects.all()
    return render(request,"story5/matkul_list.html",{
        'matkul':matkul
    })

def matkul_add(request):
    if request.method == 'POST':
        form = MatkulForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story5:matkul_list')
    else:
        form = MatkulForm()
    return render(request, "story5/matkul_add.html",{
        'form' : form
    })

def delete_matkul(request, pk):
    matkul = Matkul.objects.get(pk=pk)
    matkul.delete()
    return redirect('story5:matkul_list')

story6/views.py
from django.shortcuts import render, redirect
from .models import Event,Attendance
from .forms import EventForm, AttendanceForm

# Create your views here.
def index(request):
    event = Event.objects.all()
    attendance = Attendance.objects.all()
    return render(request, "story6/index.html",{
        'event':event,
        'attendance':attendance,
    })

def tambah_event(request):
    if request.method == 'POST':
        form1 = EventForm(request.POST)
        if form1.is_valid():
            form1.save()
            return redirect('story6:index')
    else:
        form1 = EventForm()
    return render(request, "story6/tambah_event.html",{
        'form1' : form1
    })

def tambah_attendance(request, id):
    if request.method == 'POST':
        form2 = AttendanceForm(request.POST)
        if form2.is_valid():
            validated_form = form2.save(commit=False)
            validated_form.event_id = Event.objects.get(pk=id).id
            validated_form.save()
            return redirect('story6:index')
    else:
        form2 = AttendanceForm()
    return render(request, "story6/tambah_attendance.html",{
        'form2' : form2
    })

story7/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story7/index.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.
def index(request):
    return render(request,"story8/index.html")

def fungsi_data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" +request.GET['q']
    ret = requests.get(url)
    data =json.loads(ret.content)
    print(data)
    return JsonResponse(data, safe =False)

story3/templates/story3/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Yasmin's profile</title>
    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'>
    <link href="https://id.allfont.net/allfont.css?fonts=raleway-black" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="../../static/story3/style.css" type="text/css" media="screen">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
    crossorigin="anonymous"> -->
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
</head>

<body>
    {% block content %}
    {% endblock %}

</body>
<!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script> -->

</html>

story3/templates/story3/index.html
{% extends 'story3/base.html' %}
{% load static %}

{% block content %}

<body>
    <section class="section1">
        {% include 'story3/navbar.html' %}
            <img class="decleft" src="../../static/story3/decleft.png">
            <img class="decright" src="../../static/story3/decright.png">
                <div class="home1">
                    <h2 class="nama">YASMIN<br>ZHAFIRA<br>FADHILA</h2>
                    <h2 class="npm">1906399234</h2>
                    <h2 class="angkatan">20<br>19</h2>
                <img class="foto" src="../../static/story3/fotoyasminnn.png">
            </div>
            <div class="home2">
                <p>Hi i’m Yasmin. I am an undergraduate student at Faculty of Computer
                    Science Universitas Indonesia batch 2019 . By making this website, 
                    i’m planning on giving you a little tour about my journey. 
                    </p>
            </div>
        
    </section>
    <section  class="section2">
        <div class="education" >


            <h1 id="education">EDUCATION.</h1>
            
            <div class="sekolah">
                <div class="namasekolah">
                    <h2 class="smp">SMPN 8<br> PADANG</h2>
                    <h2 class="sma">SMAN 1<br> PADANG</h2>
                    <h2 class="univ">UNIVERSITAS<br> INDONESIA</h2>
                </div>
            <img src="../../static/story3/smp.png">
            <img src="../../static/story3/sma.png">
            <img src="../../static/story3/ui.png">
        </div>
        </div>
    
    <div class="experience">
        <h1 id="experience">EXPERIENCE.</h1>
        <img class="dots" src="../../static/story3/dots.png">
        <div class="table">
        <div class="row">
            <div class="column" data-hover="Bedah fakultas jurusan">
            <h2>BKUI 20</h2>
            </div>
            <div class="column" data-hover="Secretary">
            <h2>Teater<br>Biru<br>Merah</h2>
            </div>
            <div class="column" data-hover="Staff of Registration">
            <h2>OIM UI<br>2020</h2>
            </div>
        </div>
        <div class="row">
            <div class="column" data-hover="Staff of Relation" >
                <h2>Wisuda<br>Genap<br>Fasilkom</h2>
            </div>
            <div class="column" data-hover="Staff of Business development">
                <h2>Perak<br>Fasilkom</h2>
            </div>
            <div class="column" data-hover="Staff of Public relation and Publication">
                <h2>Wisuda<br>Ganjil<br>Fasilkom</h2>
            </div>
            </div>
            <div class="row">
            <div class="column" data-hover="Ketua Bidang" >
                <h2>Bidang V<br>OSIS<br>SMAN 1<br>Padang</h2>
            </div>
            <div class="column" data-hover="PIC of Finance" >
                <h2>SMAPSiC<br>XIII+<br>Jr IX</h2>
            </div>
            <div class="column" data-hover="Project Officer">
                <h2>PKS<br>XIII</h2>
            </div>
            </div>
        </div>

    <img class="divider" src="../../static/story3/divider.png">
    
    <img class="exp" src="../../static/story3/experience.png">
    </div>
    </section>
    <section class="section3" >
        <h1 id="hobby">HOBBY AND<br>INTEREST.</h1>
        
<div class="slideshow-container">

    
    <div class="mySlides fade">
        <img src="../../static/story3/roomdecor.jpg" style="width:100%">
        <div class="text">ROOM DECORATING</div>
      </div>
    <div class="mySlides fade">
      <img src="../../static/story3/photography.jpg" style="width:100%">
      <div class="text">PHOTOGRAPHY</div>
    </div>
    <div class="mySlides fade">
      <img src="../../static/story3/makeup.jpg" style="width:100%">
      <div class="text">MAKE UP<br> & <br>SKIN CARE</div>
    </div>
    <div class="mySlides fade">
      <img src="../../static/story3/painting.jpg" style="width:100%">
      <div class="text">PAINTING</div>
    </div>
    <div class="mySlides fade">
        <img src="../../static/story3/travelling.jpg" style="width:100%">
        <div class="text">TRAVELLING</div>
      </div>
      <div class="mySlides fade">
        <img src="../../static/story3/organization.jpg" style="width:100%">
        <div class="text">MANAGING EVENT</div>
      </div>
      <div class="mySlides fade">
        <img src="../../static/story3/cooking.jpg" style="width:100%">
        <div class="text">COOKING</div>
      </div>

  
  
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>
  </div>
  <br>
  

  <div style="text-align:center">
    <span class="dot" onclick="currentSlide(1)"></span>
    <span class="dot" onclick="currentSlide(2)"></span>
    <span class="dot" onclick="currentSlide(3)"></span>
    <span class="dot" onclick="currentSlide(4)"></span>
    <span class="dot" onclick="currentSlide(5)"></span>
    <span class="dot" onclick="currentSlide(6)"></span>
    <span class="dot" onclick="currentSlide(7)"></span>
  </div>
  <script>
    var slideIndex = 1;
    showSlides(slideIndex);
    
    function plusSlides(n) {
      showSlides(slideIndex += n);
    }
    
    function currentSlide(n) {
      showSlides(slideIndex = n);
    }
    
    function showSlides(n) {
      var i;
      var slides = document.getElementsByClassName("mySlides");
      var dots = document.getElementsByClassName("dot");
      if (n > slides.length) {slideIndex = 1}    
      if (n < 1) {slideIndex = slides.length}
      for (i = 0; i < slides.length; i++) {
          slides[i].style.display = "none";  
      }
      for (i = 0; i < dots.length; i++) {
          dots[i].className = dots[i].className.replace(" active", "");
      }
      slides[slideIndex-1].style.display = "block";  
      dots[slideIndex-1].className += " active";
    }
    </script>
    </section>
</body>
<footer>
  <p>phone : 0813-3333-3333       |       <a href="mailto:yasmin.zhafira@ui.ac.id">
      yasmin.zhafira@ui.ac.id</a></p>
</footer>

{% endblock %}
</html>

story3/templates/story3/navbar.html
{% extends 'story3/base.html' %}
{% block content %}
{% load static %}
<body>
    <div class="menu">
        <button class="button button4"><a href="{% url 'homepage:index'%}">Story List</a></button>
        <ul>
            <li><a href="{% url 'story3:index'%}">HOME</a></li>
            <li><a href="{% url 'story3:profile'%}">PROFILE</a></li>
            <li><a href="{% url 'story3:index'%}#education">EDUCATION</a></li>
            <li><a href="{% url 'story3:index'%}#experience">EXPERIENCE</a></li>
            <li><a href="{% url 'story3:index'%}#hobby">INTEREST</a></li>
        </ul>
    </div>
</body>
{% endblock %}

story3/templates/story3/profile.html
{% extends 'story3/base.html' %}
{% load static %}

{% block content %}

<body>
    <section class="prof">
        {% include 'story3/navbar.html' %}
        <img class="decleft" src="../../static/story3/decleft.png">
            <img class="decright" src="../../static/story3/decright.png">
        <div class="box">
            <svg class="garis" height="650" width="500">
                <line x1="0" y1="0" x2="00" y2="900" style="stroke-width:9" />
              </svg>
            <h2>NAME</h2>
            <p>YASMIN ZHAFIRA FADHILA</p>
            <h2>D.O.B</h2>
            <p>FEBRUARY, 1ST 2001</p>
            <h2>ADDRESS</h2>
            <p>TARATAK PERMAI, PADANG</p>
            <h2>GENDER</h2>
            <p>FEMALE</p>
            <h2>BLOOD TYPE</h2>
            <p>O</p>
            <h2>MBTI</h2>
            <p>ESTP-T</p>
        </div>
    </section>
</body>
<footer>
    <p>phone : 0813-3333-3333       |       <a href="mailto:yasmin.zhafira@ui.ac.id">
        yasmin.zhafira@ui.ac.id</a></p>
</footer>
{% endblock %}
</html>

story7/templates/story7/base.html
{% load static %}
<!DOCTYPE html>
<html>

    <head>
        <title>story7.</title>
        <link rel="stylesheet" href="{% static 'story7/style.css' %}" type="text/css" media="screen">
        <link rel="stylesheet" 
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
        crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="utf-8">
        <script src='https://kit.fontawesome.com/a076d05399.js'></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'story7/script.js' %}"></script>
    </head>

<body>
    {% block content %}
    {% endblock %}
</body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</html>

story8/templates/story8/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>story8.</title>
        <link rel="stylesheet" href="../../static/story8/style.css" type="text/css" media="screen">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
        crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="utf-8">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>

    <body>
        <div class="container">
            <div class="row row-btn">
                <div class="col">
                    <a href="{% url 'homepage:index'%}"><button class="btn btn-dark" type="submit">back</button></a>
                </div>
            </div>
            <div class="row">
                <div class="col col-header">
                    <img src="../../static/story8/caribuku.png">
                </div>
                <div class="col col-header">
                    <input id="keyword" placeholder="Try to search">
                </div>
            </div>
            <div class="row row-nothing">
                <img src="../../static/story8/nothing-to-show.png">
            </div>
            
            <table class="table">
                <thead class="thead-dark" id="table-head">
                    <tr>
                    </tr>
                </thead>
                <tbody id="book_list">
                </tbody>
            </table>
        </div>
    </body>

    <script type="text/javascript" src="../../static/story8/script.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>