Story1PPW/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('story1.urls')),
    path('story5/',include('story5.urls')),
    path('story3/', include('story3.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('trialapp/', include('trialapp.urls')),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

story5/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='story5'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('matkul/<int:pk>/', views.detail, name="detail"),
    path('matkul/<int:pk>/delete', views.delete_matkul, name='delete'),
    path('matkul/', views.matkul_list, name="matkul_list"),
    path('matkul/addmatkul/', views.matkul_add, name="matkul_add"),

]

story5/models.py
from django.db import models

# Create your models here.
class Matkul(models.Model):
    name = models.CharField(max_length =30)
    dosen = models.CharField(max_length =30)
    total_credit = models.CharField(max_length =30)
    classroom = models.CharField(max_length =30)
    description= models.TextField(max_length =300)

    def __str__(self):
        return self.name

story5/forms.py
from django import forms
from .models import Matkul

class MatkulForm(forms.ModelForm):
    class Meta:
        model = Matkul
        fields =('name','dosen','total_credit','classroom','description')

story5/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.core.files.storage import FileSystemStorage
from .forms import MatkulForm
from .models import Matkul

# Create your views here.
def index(request):
    return render(request, "story5/index.html")

def detail(request,pk):
    matkul = Matkul.objects.get(pk=pk)
    return render(request, "story5/detail.html",{
        'matkul': matkul
    })

def matkul_list(request):
    matkul=Matkul.objects.all()
    return render(request,"story5/matkul_list.html",{
        'matkul':matkul
    })

def matkul_add(request):
    if request.method == 'POST':
        form = MatkulForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story5:matkul_list')
    else:
        form = MatkulForm()
    return render(request, "story5/matkul_add.html",{
        'form' : form
    })

def delete_matkul(request, pk):
    matkul = Matkul.objects.get(pk=pk)
    matkul.delete()
    return redirect('story5:matkul_list')

story5/templates/story5/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Yasmin's profile</title>
    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'>
    <link href="https://id.allfont.net/allfont.css?fonts=raleway-black" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'story5/style.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" 
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
        crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    {% block content %}
    {% endblock %}

</body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</html>

story5/templates/story5/detail-matkul.html
{% extends 'story5/base.html' %}
{% load static %}

{% block content %}
    <body>
        <section class="form-matkul">
            <img class="dots4" src="../../static/story5/dots.png">
            <img class="decright3" src="../../static/story5/decright.png">
            <button class="button button4"><a href="index.html">Home</a></button>
            <div class="judul-page-form">
                <h1>DETAIL<br>MATKUL</h1>
                
            </div>
            <div class="container3">
                <form method="POST" , action="" , enctype="multipart/form-data">
                    <div class="data-detail">
                        <h1>PPW</h1>
                        <p>Bapak dan Ibu dosen</p>
                        <br><br>
                        <p><b>Jumlah SKS     : </b>3 SKS</p><br>
                        <p><b>Semester Tahun : </b>Gasal 2020/2021</p><br>
                        <p><b>Ruangan        : </b>Kamar masing masing hehe</p><br>
                        <p><b>Deskripsi      :</b></p>
                        <p>halo ini adalah bagian deskripsi mata kuliah PPW. disini kita ngoding iya, ngedesain iya, stress iya juga
                            mana tugas ga kelar kelar hadeh
                        </p>
                    </div>
                </form>
                <a class="go-to-main" href="matkul_list.html">Kembali ke daftar matkul</a>
            </div>
        </section>
    </body>
    <footer>
        <p>phone : 0813-3333-3333       |       <a href="mailto:yasmin.zhafira@ui.ac.id">
            yasmin.zhafira@ui.ac.id</a></p>
    </footer>
    {% endblock %}
</html>

story5/templates/story5/detail.html
{% extends 'story5/base.html' %}
{% load static %}

{% block content %}

    <body>
        {% if matkul %}
        <section class="form-matkul">
            <img class="dots4" src="{% static 'story5/dots.png' %}">
            <img class="decright3" src="{% static 'story5/decright.png' %}">
            <div class="judul-page-form">
                <h1>DETAIL<br>MATKUL</h1>
                
            </div>
            <div class="container3">
                <form method="POST" , action="" , enctype="multipart/form-data">
                    <div class="data-detail">
                        <h1>{{matkul.name}}</h1>
                        <p>{{matkul.dosen}}</p>
                        <br><br>
                        <p><b>Jumlah SKS     : </b>{{matkul.total_credit}}</p><br>
                        <p><b>Semester Tahun : </b>Gasal 2020/2021</p><br>
                        <p><b>Ruangan        : </b>{{matkul.classroom}}</p><br>
                        <p><b>Deskripsi      :</b></p>
                        <p>{{matkul.description}}</p>
                    </div>
                </form>
            </div>
        </section>
        {% endif %}
    </body>
    {% endblock %}
</html>

story5/templates/story5/matkul_add.html
{% extends 'story5/base.html' %}
{% load static %}

{% block content %}
    <body>
        <h2>matkul add</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="add-btn">Tambahkan mata kuliah</button>
        </form>
    </body>
    {% endblock %}
</html>

story5/templates/story5/matkul_list.html
{% extends 'story5/base.html' %}
{% load static %}

{% block content %}
    <body>
        {% if matkul %}
        <h2>Matkul list</h2>
        <br><br><br>
        <table class="table">
            <thead>
                <tr>
                    <th>nama matkul</th>
                    <th>dosen</th>
                    <th>jumlah sks</th>
                    <th>ruangan</th>
                    <th>deskripsi</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for mata_kuliah in matkul %}
                <tr>
                    <td>{{mata_kuliah.name}}</td>
                    <td>{{mata_kuliah.dosen}}</td>
                    <td>{{mata_kuliah.total_credit}}</td>
                    <td>{{mata_kuliah.classroom}}</td>
                    <td>{{mata_kuliah.description}}</td>
                    <td><a href ="{% url 'story5:detail' mata_kuliah.pk %}"><button class="btn btn-outline-danger" type="submit">Detail</button></a></td>
                    <td><a href="{% url 'story5:delete' mata_kuliah.pk %}"><button class="btn btn-outline-danger" type="submit">Delete</button></a></td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'story5:matkul_add' %}"><button class="btn btn-danger" type="submit">Add</button></a>
        {% else %}
        <button type="submit"><a href ="{% url 'story5:matkul_add'  %}">Tambah dulu mbak</a></button>
        
        {% endif %}
    
    </body>
    {% endblock %}
</html>