Story1PPW/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('story1.urls')),
    path('story5/',include('story5.urls')),
    path('story3/', include('story3.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('trialapp/', include('trialapp.urls')),
]

homepage/urls.py
from django.urls import path, include
from . import views

app_name='homepage'

urlpatterns = [
    path('', views.index, name="index"),

]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

story3/urls.py
from django.urls import path

from . import views

app_name = 'story3'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
]

story5/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='story5'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('matkul/<int:pk>/', views.detail, name="detail"),
    path('matkul/<int:pk>/delete', views.delete_matkul, name='delete'),
    path('matkul/', views.matkul_list, name="matkul_list"),
    path('matkul/addmatkul/', views.matkul_add, name="matkul_add"),

]

story6/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='story6'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('tambah/', views.tambah_event, name="tambah_event"),
    path('daftar/<int:id>', views.tambah_attendance, name="tambah_attendance"),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='story7'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
]

story8/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='story8'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('data/', views.fungsi_data, name="data"),
]

trialapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='trialapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('accounts/login/', views.loginPage, name="loginPage"),
    path('accounts/', include('django.contrib.auth.urls')),
    path("target='_blank'", views.blank, name="blank"),
    path('data/', views.fungsi_data, name="data"),
]

homepage/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

# Create your models here.

story3/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.
class Matkul(models.Model):
    name = models.CharField(max_length =30)
    dosen = models.CharField(max_length =30)
    total_credit = models.CharField(max_length =30)
    classroom = models.CharField(max_length =30)
    description= models.TextField(max_length =300)

    def __str__(self):
        return self.name

story6/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    event_name = models.CharField(max_length = 50)
    description = models.TextField(max_length = 300)

    def __str__(self):
        return self.event_name

class Attendance(models.Model):
    name = models.CharField(max_length=30)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name ='attendances')

    def __str__(self):
        return self.name 

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story5/forms.py
from django import forms
from .models import Matkul

class MatkulForm(forms.ModelForm):
    class Meta:
        model = Matkul
        fields =('name','dosen','total_credit','classroom','description')

story6/forms.py
from django import forms
from .models import Event,Attendance

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields =('event_name','description')

class AttendanceForm(forms.ModelForm):
    class Meta:
        model = Attendance
        fields =('name',)

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "homepage/index.html")

story1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story1/index.html')

story3/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story3/index.html')

def profile(request):
    return render(request, 'story3/profile.html')

story5/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.core.files.storage import FileSystemStorage
from .forms import MatkulForm
from .models import Matkul

# Create your views here.
def index(request):
    return render(request, "story5/index.html")

def detail(request,pk):
    matkul = Matkul.objects.get(pk=pk)
    return render(request, "story5/detail.html",{
        'matkul': matkul
    })

def matkul_list(request):
    matkul=Matkul.objects.all()
    return render(request,"story5/matkul_list.html",{
        'matkul':matkul
    })

def matkul_add(request):
    if request.method == 'POST':
        form = MatkulForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story5:matkul_list')
    else:
        form = MatkulForm()
    return render(request, "story5/matkul_add.html",{
        'form' : form
    })

def delete_matkul(request, pk):
    matkul = Matkul.objects.get(pk=pk)
    matkul.delete()
    return redirect('story5:matkul_list')

story6/views.py
from django.shortcuts import render, redirect
from .models import Event,Attendance
from .forms import EventForm, AttendanceForm

# Create your views here.
def index(request):
    event = Event.objects.all()
    attendance = Attendance.objects.all()
    return render(request, "story6/index.html",{
        'event':event,
        'attendance':attendance,
    })

def tambah_event(request):
    if request.method == 'POST':
        form1 = EventForm(request.POST)
        if form1.is_valid():
            form1.save()
            return redirect('story6:index')
    else:
        form1 = EventForm()
    return render(request, "story6/tambah_event.html",{
        'form1' : form1
    })

def tambah_attendance(request, id):
    if request.method == 'POST':
        form2 = AttendanceForm(request.POST)
        if form2.is_valid():
            validated_form = form2.save(commit=False)
            validated_form.event_id = Event.objects.get(pk=id).id
            validated_form.save()
            return redirect('story6:index')
    else:
        form2 = AttendanceForm()
    return render(request, "story6/tambah_attendance.html",{
        'form2' : form2
    })

story7/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story7/index.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.
def index(request):
    return render(request,"story8/index.html")

def fungsi_data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" +request.GET['q']
    ret = requests.get(url)
    data =json.loads(ret.content)
    print(data)
    return JsonResponse(data, safe =False)

homepage/templates/homepage/index.html
<!DOCTYPE html>
<html>
    <head>
        <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'>
        <link rel="preconnect" href="https://fonts.gstatic.com"> 
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@900&display=swap" rel="stylesheet">
        <link rel="stylesheet" 
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
        crossorigin="anonymous">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="../../static/homepage/style.css">
        <title>Story story ppw yasmin</title>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <ul>
                    <li><a href="{% url 'trialapp:index'%}">session cookies<span style="font-size:40px">(new)</span></a></li>
                    <li><a href="{% url 'story8:index'%}">cariBUKU</a></li>
                    <li><a href="{% url 'story7:index'%}">accordion</a></li>
                    <li><a href="{% url 'story3:index'%}">profile</a></li>
                    <li><a href="{% url 'story1:index'%}">html intro</a></li>
                    
                    
                    
                </ul>
            </div>

            
        </div>
    </body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</html>