Story1PPW/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('story1.urls')),
    path('story5/',include('story5.urls')),
    path('story3/', include('story3.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('trialapp/', include('trialapp.urls')),
]

homepage/urls.py
from django.urls import path, include
from . import views

app_name='homepage'

urlpatterns = [
    path('', views.index, name="index"),

]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

trialapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='trialapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('accounts/login/', views.loginPage, name="loginPage"),
    path('accounts/', include('django.contrib.auth.urls')),
    path("target='_blank'", views.blank, name="blank"),
    path('data/', views.fungsi_data, name="data"),
]

trialapp/models.py
from django.db import models

# Create your models here.

trialapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    username = forms.CharField(label="")
    email = forms.CharField(label="")
    password1 = forms.CharField(widget=forms.PasswordInput(),label="")
    password2 = forms.CharField(widget=forms.PasswordInput(),label="")
    username.widget.attrs.update({'placeholder':'username', 'class':'input-box'})
    email.widget.attrs.update({'placeholder':'email', 'class':'input-box'})
    password1.widget.attrs.update({'placeholder':'enter password', 'class':'input-box'})
    password2.widget.attrs.update({'placeholder':'re-enter password', 'class':'input-box'})
    class Meta:
        model = User
        fields = ['username' , 'email', 'password1', 'password2']

trialapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .forms import CreateUserForm
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.http import JsonResponse
import requests
import json

# Create your views here.
def index(request):
    return render(request,"trialapp/index.html")

def blank(request):
    return redirect("trialapp:index")

def signup(request):
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request,'registration success')

            return redirect('trialapp:login')
    else:
        form = CreateUserForm()
    return render(request,"trialapp/registration.html",{
        'form':form
    })

def loginPage(request):
	if request.user.is_authenticated:
		return redirect('trialapp:index')
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect('trialapp:index')
			else:
				messages.info(request, 'username or password is incorrect')

		context = {}
		return render(request, 'registration/login.html', context)

def fungsi_data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" +request.GET['q']
    ret = requests.get(url)
    data =json.loads(ret.content)

    if not request.user.is_authenticated:
        i=0
        for x in data['items']:
            data['items'][i]['volumeInfo']['previewLink'] = ''
            i+=1
    return JsonResponse(data, safe =False)

trialapp/templates/trialapp/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>cariBUKU.</title>
        <link rel="stylesheet" href="../../static/trialapp/style.css" type="text/css" media="screen">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
        crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="utf-8">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <img src="../../static/trialapp/caribuku.svg">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% if user.is_authenticated%}
                        <li class="nav-item">
                            <span class="navbar-brand mb-0 h1">halo, {{user.username}}!</span>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        
                            {% if user.is_authenticated%}
                            <li>
                                <a class="nav-link" href="{% url 'trialapp:logout'%}">
                                    <button class="btn btn-warning back-btn" type="submit">Log out</button>
                                </a>
                            </li>
                            {% else %}
                            <li>
                                <a class="nav-link" href="{% url 'trialapp:login'%}">
                                    <button class="btn btn-warning back-btn" type="submit">Log in</button>
                                </a>
                            </li>
                            {% endif %}
                            <form class="form-inline">
                            <div class="nav-link">
                                <button class="btn btn-dark back-btn" type="submit"><a class="back-back"href="{% url 'homepage:index' %}">back</a></button>
                            </div>
                            <input id="keyword" class="form-control mr-sm-2" type="search" placeholder="Try to search" aria-label="Search">
                        </form>
                    </li>
                </ul> 
            </div>
        </nav>
    
        <div class="container">
            {% if not user.is_authenticated%}
            <div class="alert alert-warning alert-utk-login" role="alert">
                <p>Please Log in to see books previews</p>
            </div>
            {% endif %}
            <div class="row row-nothing">
                <img src="../../static/trialapp/nothing-to-show.svg">
            </div>
            
            <table class="table">
                <thead class="thead-dark" id="table-head">
                    <tr>
                    </tr>
                </thead>
                <tbody id="book_list">
                </tbody>
            </table>
        </div>
    </body>
    <script type="text/javascript" src="../../static/trialapp/script.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

trialapp/templates/trialapp/registration.html
<!DOCTYPE html>
<html>
    
<head>
    <title>cariBUKU|Registration</title>
    <link rel="stylesheet" href="../../static/trialapp/style.css" type="text/css" media="screen">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
</head>
<body class="register">
	<div class="container h-100">
        <div class="row">
            <div class="col-lg">
                <img class="logo-reg-login" src="../../../static/trialapp/logo.svg">
                <img class="logo-small" src="../../../static/trialapp/logo-small.svg">
            </div>
            <div class="col-lg">
                <div class="register-box">
                    <div class="d-flex justify-content-center form-container">
                        <form method="POST" action="">
                            {% csrf_token %}
                            {{form.as_p}}
                            </div>
                            <a class="d-flex justify-content-center link-to-other" href="{% url 'trialapp:loginPage' %}">already have an account? log in</a>
                            <div class="d-flex justify-content-center mt-4">
                                <input class="btn btn-dark" type="submit" value="register">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
	</div>
</body>
</html>